--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.0

-- Started on 2025-03-25 22:44:08

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--




--
-- TOC entry 873 (class 1247 OID 16538)
-- Name: enum_auction_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE enum_auction_status AS ENUM (
    'listed',
    'bidding',
    'sold',
    'expired'
);


--
-- TOC entry 864 (class 1247 OID 16458)
-- Name: enum_bid_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE enum_bid_status AS ENUM (
    'active',
    'outbid',
    'won'
);


--
-- TOC entry 858 (class 1247 OID 16434)
-- Name: enum_category; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE enum_category AS ENUM (
    'electronics',
    'books',
    'home',
    'clothing',
    'sports',
    'others'
);



--
-- TOC entry 861 (class 1247 OID 16448)
-- Name: enum_condition; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE enum_condition AS ENUM (
    'new',
    'like-new',
    'good',
    'acceptable'
);


--
-- TOC entry 867 (class 1247 OID 16466)
-- Name: enum_payment_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE enum_payment_status AS ENUM (
    'pending',
    'completed',
    'failed',
    'refunded'
);



SET default_tablespace = '';

SET default_table_access_method = heap;




--
-- TOC entry 220 (class 1259 OID 16418)
-- Name: auctions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE auctions (
    auction_id integer NOT NULL,
    item_id integer NOT NULL,
    start_price numeric(18,0) NOT NULL,
    current_price numeric(18,0) NOT NULL,
    buy_it_now_price numeric(18,0) NOT NULL,
    bid_start_time timestamp without time zone DEFAULT now() NOT NULL,
    bid_end_time timestamp without time zone NOT NULL,
    auction_status enum_auction_status NOT NULL
);



--
-- TOC entry 223 (class 1259 OID 16547)
-- Name: auction_auction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE auctions ALTER COLUMN auction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auction_auction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16496)
-- Name: bids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE bids (
    bid_id integer NOT NULL,
    bidder_id character varying(30) NOT NULL,
    auction_id integer NOT NULL,
    bid_price numeric(18,0) NOT NULL,
    bid_time timestamp without time zone DEFAULT now() NOT NULL,
    bid_status public.enum_bid_status NOT NULL
);



--
-- TOC entry 226 (class 1259 OID 16550)
-- Name: bid_bid_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE bids ALTER COLUMN bid_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME bid_bid_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16516)
-- Name: billing; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE billing (
    billing_id integer NOT NULL,
    item_id integer NOT NULL,
    buyer_id character varying(30) NOT NULL,
    seller_id character varying(30) NOT NULL,
    final_price numeric(18,0) DEFAULT 0 NOT NULL,
    transaction_time timestamp without time zone DEFAULT now() NOT NULL,
    payment_status public.enum_payment_status NOT NULL
);



--
-- TOC entry 225 (class 1259 OID 16549)
-- Name: billing_billing_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE billing ALTER COLUMN billing_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME billing_billing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16405)
-- Name: items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.items (
    item_id integer NOT NULL,
    item_desc character varying(1000),
    seller_id character varying(30) NOT NULL,
    auction_id integer NOT NULL,
    item_category public.enum_category NOT NULL,
    item_condition public.enum_condition NOT NULL
);


--
-- TOC entry 224 (class 1259 OID 16548)
-- Name: item_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME item_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16394)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE users (
    user_id character varying(20) NOT NULL,
    password character varying(64) NOT NULL,
    is_privileged boolean DEFAULT false NOT NULL
);



--
-- TOC entry 4791 (class 2606 OID 16422)
-- Name: auctions auction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY auctions
    ADD CONSTRAINT auction_pkey PRIMARY KEY (auction_id);


--
-- TOC entry 4793 (class 2606 OID 16501)
-- Name: bids bid_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bids
    ADD CONSTRAINT bid_pkey PRIMARY KEY (bid_id);


--
-- TOC entry 4795 (class 2606 OID 16521)
-- Name: billing billing_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY billing
    ADD CONSTRAINT billing_pkey PRIMARY KEY (billing_id);


--
-- TOC entry 4789 (class 2606 OID 16411)
-- Name: items item_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY items
    ADD CONSTRAINT item_pkey PRIMARY KEY (item_id);


--
-- TOC entry 4786 (class 2606 OID 16398)
-- Name: users user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY users
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4787 (class 1259 OID 16417)
-- Name: item_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX item_index ON items USING btree (item_id);


--
-- TOC entry 4796 (class 2606 OID 16428)
-- Name: items auction_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY items
    ADD CONSTRAINT auction_id_foreign FOREIGN KEY (auction_id) REFERENCES auctions(auction_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4799 (class 2606 OID 16511)
-- Name: bids foreign_auction; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bids
    ADD CONSTRAINT foreign_auction FOREIGN KEY (auction_id) REFERENCES auctions(auction_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4800 (class 2606 OID 16506)
-- Name: bids foreign_bidder; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY bids
    ADD CONSTRAINT foreign_bidder FOREIGN KEY (bidder_id) REFERENCES users(user_id);


--
-- TOC entry 4801 (class 2606 OID 16527)
-- Name: billing foreign_buyer; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY billing
    ADD CONSTRAINT foreign_buyer FOREIGN KEY (buyer_id) REFERENCES users(user_id);


--
-- TOC entry 4802 (class 2606 OID 16522)
-- Name: billing foreign_item; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY billing
    ADD CONSTRAINT foreign_item FOREIGN KEY (item_id) REFERENCES items(item_id);


--
-- TOC entry 4803 (class 2606 OID 16532)
-- Name: billing foreign_seller; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY billing
    ADD CONSTRAINT foreign_seller FOREIGN KEY (seller_id) REFERENCES users(user_id);


--
-- TOC entry 4798 (class 2606 OID 16423)
-- Name: auctions item_id_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY auctions
    ADD CONSTRAINT item_id_foreign FOREIGN KEY (item_id) REFERENCES items(item_id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 4797 (class 2606 OID 16412)
-- Name: items seller_foreign; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY items
    ADD CONSTRAINT seller_foreign FOREIGN KEY (seller_id) REFERENCES users(user_id) ON UPDATE CASCADE ON DELETE CASCADE;


-- Completed on 2025-03-25 22:44:09

--
-- PostgreSQL database dump complete
--

